<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'flag_path' => 'images/flags/af.svg'],
            ['name' => 'Albania', 'code' => 'AL', 'flag_path' => 'images/flags/al.svg'],
            ['name' => 'Algeria', 'code' => 'DZ', 'flag_path' => 'images/flags/dz.svg'],
            ['name' => 'Andorra', 'code' => 'AD', 'flag_path' => 'images/flags/ad.svg'],
            ['name' => 'Angola', 'code' => 'AO', 'flag_path' => 'images/flags/ao.svg'],
            ['name' => 'Argentina', 'code' => 'AR', 'flag_path' => 'images/flags/ar.svg'],
            ['name' => 'Armenia', 'code' => 'AM', 'flag_path' => 'images/flags/am.svg'],
            ['name' => 'Austria', 'code' => 'AT', 'flag_path' => 'images/flags/at.svg'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'flag_path' => 'images/flags/az.svg'],
            ['name' => 'Bahamas', 'code' => 'BS', 'flag_path' => 'images/flags/bs.svg'],
            ['name' => 'Bahrain', 'code' => 'BH', 'flag_path' => 'images/flags/bh.svg'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'flag_path' => 'images/flags/bd.svg'],
            ['name' => 'Barbados', 'code' => 'BB', 'flag_path' => 'images/flags/bb.svg'],
            ['name' => 'Belarus', 'code' => 'BY', 'flag_path' => 'images/flags/by.svg'],
            ['name' => 'Belgium', 'code' => 'BE', 'flag_path' => 'images/flags/be.svg'],
            ['name' => 'Belize', 'code' => 'BZ', 'flag_path' => 'images/flags/bz.svg'],
            ['name' => 'Benin', 'code' => 'BJ', 'flag_path' => 'images/flags/bj.svg'],
            ['name' => 'Bhutan', 'code' => 'BT', 'flag_path' => 'images/flags/bt.svg'],
            ['name' => 'Bolivia', 'code' => 'BO', 'flag_path' => 'images/flags/bo.svg'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'flag_path' => 'images/flags/ba.svg'],
            ['name' => 'Botswana', 'code' => 'BW', 'flag_path' => 'images/flags/bw.svg'],
            ['name' => 'Brazil', 'code' => 'BR', 'flag_path' => 'images/flags/br.svg'],
            ['name' => 'Brunei', 'code' => 'BN', 'flag_path' => 'images/flags/bn.svg'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'flag_path' => 'images/flags/bg.svg'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'flag_path' => 'images/flags/bf.svg'],
            ['name' => 'Burundi', 'code' => 'BI', 'flag_path' => 'images/flags/bi.svg'],
            ['name' => 'Cambodia', 'code' => 'KH', 'flag_path' => 'images/flags/kh.svg'],
            ['name' => 'Cameroon', 'code' => 'CM', 'flag_path' => 'images/flags/cm.svg'],
            ['name' => 'Canada', 'code' => 'CA', 'flag_path' => 'images/flags/ca.svg'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'flag_path' => 'images/flags/cv.svg'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'flag_path' => 'images/flags/cf.svg'],
            ['name' => 'Chad', 'code' => 'TD', 'flag_path' => 'images/flags/td.svg'],
            ['name' => 'Chile', 'code' => 'CL', 'flag_path' => 'images/flags/cl.svg'],
            ['name' => 'China', 'code' => 'CN', 'flag_path' => 'images/flags/cn.svg'],
            ['name' => 'Colombia', 'code' => 'CO', 'flag_path' => 'images/flags/co.svg'],
            ['name' => 'Comoros', 'code' => 'KM', 'flag_path' => 'images/flags/km.svg'],
            ['name' => 'Congo', 'code' => 'CG', 'flag_path' => 'images/flags/cg.svg'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'flag_path' => 'images/flags/cr.svg'],
            ['name' => 'Croatia', 'code' => 'HR', 'flag_path' => 'images/flags/hr.svg'],
            ['name' => 'Cuba', 'code' => 'CU', 'flag_path' => 'images/flags/cu.svg'],
            ['name' => 'Cyprus', 'code' => 'CY', 'flag_path' => 'images/flags/cy.svg'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'flag_path' => 'images/flags/cz.svg'],
            ['name' => 'Denmark', 'code' => 'DK', 'flag_path' => 'images/flags/dk.svg'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'flag_path' => 'images/flags/dj.svg'],
            ['name' => 'Dominica', 'code' => 'DM', 'flag_path' => 'images/flags/dm.svg'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'flag_path' => 'images/flags/do.svg'],
            ['name' => 'Ecuador', 'code' => 'EC', 'flag_path' => 'images/flags/ec.svg'],
            ['name' => 'Egypt', 'code' => 'EG', 'flag_path' => 'images/flags/eg.svg'],
            ['name' => 'El Salvador', 'code' => 'SV', 'flag_path' => 'images/flags/sv.svg'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'flag_path' => 'images/flags/gq.svg'],
            ['name' => 'Eritrea', 'code' => 'ER', 'flag_path' => 'images/flags/er.svg'],
            ['name' => 'Estonia', 'code' => 'EE', 'flag_path' => 'images/flags/ee.svg'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'flag_path' => 'images/flags/et.svg'],
            ['name' => 'Fiji', 'code' => 'FJ', 'flag_path' => 'images/flags/fj.svg'],
            ['name' => 'Finland', 'code' => 'FI', 'flag_path' => 'images/flags/fi.svg'],
            ['name' => 'France', 'code' => 'FR', 'flag_path' => 'images/flags/fr.svg'],
            ['name' => 'Gabon', 'code' => 'GA', 'flag_path' => 'images/flags/ga.svg'],
            ['name' => 'Gambia', 'code' => 'GM', 'flag_path' => 'images/flags/gm.svg'],
            ['name' => 'Georgia', 'code' => 'GE', 'flag_path' => 'images/flags/ge.svg'],
            ['name' => 'Germany', 'code' => 'DE', 'flag_path' => 'images/flags/de.svg'],
            ['name' => 'Ghana', 'code' => 'GH', 'flag_path' => 'images/flags/gh.svg'],
            ['name' => 'Greece', 'code' => 'GR', 'flag_path' => 'images/flags/gr.svg'],
            ['name' => 'Grenada', 'code' => 'GD', 'flag_path' => 'images/flags/gd.svg'],
            ['name' => 'Guatemala', 'code' => 'GT', 'flag_path' => 'images/flags/gt.svg'],
            ['name' => 'Guinea', 'code' => 'GN', 'flag_path' => 'images/flags/gn.svg'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'flag_path' => 'images/flags/gw.svg'],
            ['name' => 'Guyana', 'code' => 'GY', 'flag_path' => 'images/flags/gy.svg'],
            ['name' => 'Haiti', 'code' => 'HT', 'flag_path' => 'images/flags/ht.svg'],
            ['name' => 'Honduras', 'code' => 'HN', 'flag_path' => 'images/flags/hn.svg'],
            ['name' => 'Hungary', 'code' => 'HU', 'flag_path' => 'images/flags/hu.svg'],
            ['name' => 'Iceland', 'code' => 'IS', 'flag_path' => 'images/flags/is.svg'],
            ['name' => 'India', 'code' => 'IN', 'flag_path' => 'images/flags/in.svg'],
            ['name' => 'Indonesia', 'code' => 'ID', 'flag_path' => 'images/flags/id.svg'],
            ['name' => 'Iran', 'code' => 'IR', 'flag_path' => 'images/flags/ir.svg'],
            ['name' => 'Iraq', 'code' => 'IQ', 'flag_path' => 'images/flags/iq.svg'],
            ['name' => 'Ireland', 'code' => 'IE', 'flag_path' => 'images/flags/ie.svg'],
            ['name' => 'Israel', 'code' => 'IL', 'flag_path' => 'images/flags/il.svg'],
            ['name' => 'Italy', 'code' => 'IT', 'flag_path' => 'images/flags/it.svg'],
            ['name' => 'Jamaica', 'code' => 'JM', 'flag_path' => 'images/flags/jm.svg'],
            ['name' => 'Japan', 'code' => 'JP', 'flag_path' => 'images/flags/jp.svg'],
            ['name' => 'Jordan', 'code' => 'JO', 'flag_path' => 'images/flags/jo.svg'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'flag_path' => 'images/flags/kz.svg'],
            ['name' => 'Kenya', 'code' => 'KE', 'flag_path' => 'images/flags/ke.svg'],
            ['name' => 'Kiribati', 'code' => 'KI', 'flag_path' => 'images/flags/ki.svg'],
            ['name' => 'Kuwait', 'code' => 'KW', 'flag_path' => 'images/flags/kw.svg'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'flag_path' => 'images/flags/kg.svg'],
            ['name' => 'Laos', 'code' => 'LA', 'flag_path' => 'images/flags/la.svg'],
            ['name' => 'Latvia', 'code' => 'LV', 'flag_path' => 'images/flags/lv.svg'],
            ['name' => 'Lebanon', 'code' => 'LB', 'flag_path' => 'images/flags/lb.svg'],
            ['name' => 'Lesotho', 'code' => 'LS', 'flag_path' => 'images/flags/ls.svg'],
            ['name' => 'Liberia', 'code' => 'LR', 'flag_path' => 'images/flags/lr.svg'],
            ['name' => 'Libya', 'code' => 'LY', 'flag_path' => 'images/flags/ly.svg'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'flag_path' => 'images/flags/li.svg'],
            ['name' => 'Lithuania', 'code' => 'LT', 'flag_path' => 'images/flags/lt.svg'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'flag_path' => 'images/flags/lu.svg'],
            ['name' => 'Madagascar', 'code' => 'MG', 'flag_path' => 'images/flags/mg.svg'],
            ['name' => 'Malawi', 'code' => 'MW', 'flag_path' => 'images/flags/mw.svg'],
            ['name' => 'Malaysia', 'code' => 'MY', 'flag_path' => 'images/flags/my.svg'],
            ['name' => 'Maldives', 'code' => 'MV', 'flag_path' => 'images/flags/mv.svg'],
            ['name' => 'Mali', 'code' => 'ML', 'flag_path' => 'images/flags/ml.svg'],
            ['name' => 'Malta', 'code' => 'MT', 'flag_path' => 'images/flags/mt.svg'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'flag_path' => 'images/flags/mh.svg'],
            ['name' => 'Mauritania', 'code' => 'MR', 'flag_path' => 'images/flags/mr.svg'],
            ['name' => 'Mauritius', 'code' => 'MU', 'flag_path' => 'images/flags/mu.svg'],
            ['name' => 'Mexico', 'code' => 'MX', 'flag_path' => 'images/flags/mx.svg'],
            ['name' => 'Micronesia', 'code' => 'FM', 'flag_path' => 'images/flags/fm.svg'],
            ['name' => 'Moldova', 'code' => 'MD', 'flag_path' => 'images/flags/md.svg'],
            ['name' => 'Monaco', 'code' => 'MC', 'flag_path' => 'images/flags/mc.svg'],
            ['name' => 'Mongolia', 'code' => 'MN', 'flag_path' => 'images/flags/mn.svg'],
            ['name' => 'Montenegro', 'code' => 'ME', 'flag_path' => 'images/flags/me.svg'],
            ['name' => 'Morocco', 'code' => 'MA', 'flag_path' => 'images/flags/ma.svg'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'flag_path' => 'images/flags/mz.svg'],
            ['name' => 'Myanmar', 'code' => 'MM', 'flag_path' => 'images/flags/mm.svg'],
            ['name' => 'Namibia', 'code' => 'NA', 'flag_path' => 'images/flags/na.svg'],
            ['name' => 'Nauru', 'code' => 'NR', 'flag_path' => 'images/flags/nr.svg'],
            ['name' => 'Nepal', 'code' => 'NP', 'flag_path' => 'images/flags/np.svg'],
            ['name' => 'Netherlands', 'code' => 'NL', 'flag_path' => 'images/flags/nl.svg'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'flag_path' => 'images/flags/nz.svg'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'flag_path' => 'images/flags/ni.svg'],
            ['name' => 'Niger', 'code' => 'NE', 'flag_path' => 'images/flags/ne.svg'],
            ['name' => 'Nigeria', 'code' => 'NG', 'flag_path' => 'images/flags/ng.svg'],
            ['name' => 'North Korea', 'code' => 'KP', 'flag_path' => 'images/flags/kp.svg'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'flag_path' => 'images/flags/mk.svg'],
            ['name' => 'Norway', 'code' => 'NO', 'flag_path' => 'images/flags/no.svg'],
            ['name' => 'Oman', 'code' => 'OM', 'flag_path' => 'images/flags/om.svg'],
            ['name' => 'Pakistan', 'code' => 'PK', 'flag_path' => 'images/flags/pk.svg'],
            ['name' => 'Palau', 'code' => 'PW', 'flag_path' => 'images/flags/pw.svg'],
            ['name' => 'Palestine', 'code' => 'PS', 'flag_path' => 'images/flags/ps.svg'],
            ['name' => 'Panama', 'code' => 'PA', 'flag_path' => 'images/flags/pa.svg'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'flag_path' => 'images/flags/pg.svg'],
            ['name' => 'Paraguay', 'code' => 'PY', 'flag_path' => 'images/flags/py.svg'],
            ['name' => 'Peru', 'code' => 'PE', 'flag_path' => 'images/flags/pe.svg'],
            ['name' => 'Philippines', 'code' => 'PH', 'flag_path' => 'images/flags/ph.svg'],
            ['name' => 'Poland', 'code' => 'PL', 'flag_path' => 'images/flags/pl.svg'],
            ['name' => 'Portugal', 'code' => 'PT', 'flag_path' => 'images/flags/pt.svg'],
            ['name' => 'Qatar', 'code' => 'QA', 'flag_path' => 'images/flags/qa.svg'],
            ['name' => 'Romania', 'code' => 'RO', 'flag_path' => 'images/flags/ro.svg'],
            ['name' => 'Russia', 'code' => 'RU', 'flag_path' => 'images/flags/ru.svg'],
            ['name' => 'Rwanda', 'code' => 'RW', 'flag_path' => 'images/flags/rw.svg'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'flag_path' => 'images/flags/kn.svg'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'flag_path' => 'images/flags/lc.svg'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'flag_path' => 'images/flags/vc.svg'],
            ['name' => 'Samoa', 'code' => 'WS', 'flag_path' => 'images/flags/ws.svg'],
            ['name' => 'San Marino', 'code' => 'SM', 'flag_path' => 'images/flags/sm.svg'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'flag_path' => 'images/flags/st.svg'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'flag_path' => 'images/flags/sa.svg'],
            ['name' => 'Senegal', 'code' => 'SN', 'flag_path' => 'images/flags/sn.svg'],
            ['name' => 'Serbia', 'code' => 'RS', 'flag_path' => 'images/flags/rs.svg'],
            ['name' => 'Seychelles', 'code' => 'SC', 'flag_path' => 'images/flags/sc.svg'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'flag_path' => 'images/flags/sl.svg'],
            ['name' => 'Singapore', 'code' => 'SG', 'flag_path' => 'images/flags/sg.svg'],
            ['name' => 'Slovakia', 'code' => 'SK', 'flag_path' => 'images/flags/sk.svg'],
            ['name' => 'Slovenia', 'code' => 'SI', 'flag_path' => 'images/flags/si.svg'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'flag_path' => 'images/flags/sb.svg'],
            ['name' => 'Somalia', 'code' => 'SO', 'flag_path' => 'images/flags/so.svg'],
            ['name' => 'South Africa', 'code' => 'ZA', 'flag_path' => 'images/flags/za.svg'],
            ['name' => 'South Korea', 'code' => 'KR', 'flag_path' => 'images/flags/kr.svg'],
            ['name' => 'South Sudan', 'code' => 'SS', 'flag_path' => 'images/flags/ss.svg'],
            ['name' => 'Spain', 'code' => 'ES', 'flag_path' => 'images/flags/es.svg'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'flag_path' => 'images/flags/lk.svg'],
            ['name' => 'Sudan', 'code' => 'SD', 'flag_path' => 'images/flags/sd.svg'],
            ['name' => 'Suriname', 'code' => 'SR', 'flag_path' => 'images/flags/sr.svg'],
            ['name' => 'Sweden', 'code' => 'SE', 'flag_path' => 'images/flags/se.svg'],
            ['name' => 'Switzerland', 'code' => 'CH', 'flag_path' => 'images/flags/ch.svg'],
            ['name' => 'Syria', 'code' => 'SY', 'flag_path' => 'images/flags/sy.svg'],
            ['name' => 'Taiwan', 'code' => 'TW', 'flag_path' => 'images/flags/tw.svg'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'flag_path' => 'images/flags/tj.svg'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'flag_path' => 'images/flags/tz.svg'],
            ['name' => 'Thailand', 'code' => 'TH', 'flag_path' => 'images/flags/th.svg'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'flag_path' => 'images/flags/tl.svg'],
            ['name' => 'Togo', 'code' => 'TG', 'flag_path' => 'images/flags/tg.svg'],
            ['name' => 'Tonga', 'code' => 'TO', 'flag_path' => 'images/flags/to.svg'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'flag_path' => 'images/flags/tt.svg'],
            ['name' => 'Tunisia', 'code' => 'TN', 'flag_path' => 'images/flags/tn.svg'],
            ['name' => 'Turkey', 'code' => 'TR', 'flag_path' => 'images/flags/tr.svg'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'flag_path' => 'images/flags/tm.svg'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'flag_path' => 'images/flags/tv.svg'],
            ['name' => 'Uganda', 'code' => 'UG', 'flag_path' => 'images/flags/ug.svg'],
            ['name' => 'Ukraine', 'code' => 'UA', 'flag_path' => 'images/flags/ua.svg'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'flag_path' => 'images/flags/ae.svg'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'flag_path' => 'images/flags/gb.svg'],
            ['name' => 'United States', 'code' => 'US', 'flag_path' => 'images/flags/us.svg'],
            ['name' => 'Uruguay', 'code' => 'UY', 'flag_path' => 'images/flags/uy.svg'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'flag_path' => 'images/flags/uz.svg'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'flag_path' => 'images/flags/vu.svg'],
            ['name' => 'Vatican City', 'code' => 'VA', 'flag_path' => 'images/flags/va.svg'],
            ['name' => 'Venezuela', 'code' => 'VE', 'flag_path' => 'images/flags/ve.svg'],
            ['name' => 'Vietnam', 'code' => 'VN', 'flag_path' => 'images/flags/vn.svg'],
            ['name' => 'Yemen', 'code' => 'YE', 'flag_path' => 'images/flags/ye.svg'],
            ['name' => 'Zambia', 'code' => 'ZM', 'flag_path' => 'images/flags/zm.svg'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'flag_path' => 'images/flags/zw.svg'],
        ];

        DB::table('countries')->truncate(); // Clear existing data

        foreach ($countries as $country) {
            DB::table('countries')->insert(array_merge($country, [
                'status' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
